### ISSUE TITLE
Uncaught ImagickException: Failed to read the file

### ISSUE THREAD

**Issue by raintonr** [bkbilly/Hikvision-Site#5]
Trying to install today on Fedora FC36. Apache httpd 2.4.54 + PHP 8.1.3.

I see this error trying to fetch `/dispatcher.php?action=videopicture` in the browser:

```
<b>Fatal error</b>:  Uncaught ImagickException: Failed to read the file in /usr/share/Hikvision-Site/dispatcher.php:152
  | Stack trace:
  | #0 /usr/share/Hikvision-Site/dispatcher.php(154): Imagick-&gt;__construct()
  | #1 /usr/share/Hikvision-Site/dispatcher.php(25): videopicture()
  | #2 {main}
  | thrown in <b>/usr/share/Hikvision-Site/dispatcher.php</b> on line <b>152</b><br />
```

Everything in .htaccess configured correctly. Verified as I put logging in the code to print out the URL. Even tried fetching the URL with PHPs `file_get_contents` which also reported an error: `Failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized`.

**Comment by bkbilly** [comment]
I am not sure how to fix your issue, but you can try installing it using docker:
https://hub.docker.com/r/bkbillybk/hikvision_site

**Comment by DanielO** [comment]
I had this problem also, I fixed it with this diff:
````
diff --git a/dispatcher.php b/dispatcher.php
index 1257c01..5a9437a 100644
--- a/dispatcher.php
+++ b/dispatcher.php
@@ -149,7 +149,10 @@
                                $stack = new Imagick();
                                foreach ($camIPs as $index => $ip) {
                                        $url = 'http://'.$camAuths[$index].'@'.$ip.'/Streaming/channels/102/picture';
-                                       $stack->addImage(new Imagick($url));
+                                       $image = file_get_contents($url);
+                                       $img = new Imagick();
+                                       $img->readImageBlob($image);
+                                       $stack->addImage($img);
                                }
                                $sizex = intval(sizeof($camIPs) / 2);
                                $sizey = sizeof($camIPs) - $sizex;
````
